patcg-individual-drafts/private-aggregation-api

- spec.bs
Updates how global scopes are referred to in the spec. Requires some minor changes to the Protected Audiences (formerly FLEDGE) spec for this change to make sense. Those are being made [here](https://github.com/WICG/turtledove/pull/546).
***
<a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/pull/27.html" title="Last updated on Apr 19, 2023, 6:50 PM UTC (e7ce93c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/27/5b8a817...e7ce93c.html" title="Last updated on Apr 19, 2023, 6:50 PM UTC (e7ce93c)">Diff</a>
> Spec: replace global scope names

- spec.bs
The API has been renamed, so this updates references in the spec. See https://privacysandbox.com/intl/en_us/news/protected-audience-api-our-new-name-for-fledge
***
<a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/pull/34.html" title="Last updated on May 3, 2023, 10:28 PM UTC (2ac3c72)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/34/3d814a3...2ac3c72.html" title="Last updated on May 3, 2023, 10:28 PM UTC (2ac3c72)">Diff</a>
> Spec: Replace FLEDGE with Protected Audience API

- README.md
Updates explainer to reflect old changes to the aggregation service
> Remove stale references to Privacy Budget Key

- README.md
Updates the explainer to reflect old naming changes in Shared Storage. Also adds a small amount of text to clarify certain parts.
> Minor explainer updates

- README.md
Switches from per-origin per-day budgets to per-site per-10 min. Also adds a new per-site per-day looser budget as a backstop to prevent worst-case leakage.
See original proposal here:
https://github.com/patcg-individual-drafts/private-aggregation-api/issues/23#issuecomment-1500648899
> Update contribution bound and add new 'backstop' bound

- README.md
- spec.bs
Changes sendHistogramReport() to contributeToHistogram() and reportContributionForEvent() to contributeToHistogramOnEvent(). Functionality is otherwise unchanged.
See issue #44.
***
<a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/pull/48.html" title="Last updated on May 19, 2023, 9:08 PM UTC (5a1d70c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/48/bdbbd63...5a1d70c.html" title="Last updated on May 19, 2023, 9:08 PM UTC (5a1d70c)">Diff</a>
> Rename API functions to be more accurate and consistent

- README.md
The `debug/` infix is placed in the wrong spot currently.
> Fix debug reporting path

- README.md
We shouldn't have updated "debug_key" to "debugKey" in the JSON report itself -- only in the javascript.
> Use debug_key in JSON report

- spec.bs
Creates new exported algorithms and one algorithm to be overriden. This cl doesn't actually move any content to other specs, but is a step to making that simpler. This change also addresses batching, by defining the batching scopes more completely.
***
<a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/pull/51.html" title="Last updated on Jun 9, 2023, 7:47 PM UTC (ada0439)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/51/b69953e...ada0439.html" title="Last updated on Jun 9, 2023, 7:47 PM UTC (ada0439)">Diff</a>
> Change API layering in spec

- spec.bs
Removes the unnecessary for="PrivateAggregation" namespacing for algorithms. Methods on the PrivateAggregation object retain their namespacing
***
<a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/pull/54.html" title="Last updated on Jun 9, 2023, 7:56 PM UTC (cb1b416)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/54/3d32307...cb1b416.html" title="Last updated on Jun 9, 2023, 7:56 PM UTC (cb1b416)">Diff</a>
> Spec: remove PrivateAggregation namespacing for algorithms

- spec.bs
The privacy and security considerations cl reintroduced some of this namespacing, causing bikeshed errors.
***
<a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/pull/58.html" title="Last updated on Jun 9, 2023, 8:26 PM UTC (051185b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/58/69b640f...051185b.html" title="Last updated on Jun 9, 2023, 8:26 PM UTC (051185b)">Diff</a>
> Spec: Finish removing unnecessary PrivateAggregation namespacing

- spec.bs
Fills in many missing pieces from the Protected Audience monkey patches
***
<a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/pull/63.html" title="Last updated on Jun 20, 2023, 7:39 PM UTC (e53f1bd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/63/f2a110f...e53f1bd.html" title="Last updated on Jun 20, 2023, 7:39 PM UTC (e53f1bd)">Diff</a>
> Spec: Fill in Protected Audience extensions

- spec.bs
Defines the "private-aggregation" permissions policy and plumbs values through. Improves other algorithm's plumbing as a drive-by.
***
<a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/pull/66.html" title="Last updated on Jun 20, 2023, 7:52 PM UTC (e1e9da0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/66/270f49e...e1e9da0.html" title="Last updated on Jun 20, 2023, 7:52 PM UTC (e1e9da0)">Diff</a>
> Spec: Permissions policy integration

- spec.bs
Adds hyperlinks when throwing an exception.
***
<a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/pull/76.html" title="Last updated on Jun 23, 2023, 7:35 PM UTC (243dcde)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/76/b4028f7...243dcde.html" title="Last updated on Jun 23, 2023, 7:35 PM UTC (243dcde)">Diff</a>
> Spec: Link "throw" to definition

- spec.bs
Guards the privateAggregation object directly instead of guarding each API function. This aligns with the implementation and reduces duplicate logic. Also reworks the wording of the permissions policy integration as a drive-by.
***
<a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/pull/75.html" title="Last updated on Jul 6, 2023, 6:09 PM UTC (58ce26f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/75/ddb61fd...58ce26f.html" title="Last updated on Jul 6, 2023, 6:09 PM UTC (58ce26f)">Diff</a>
> Spec: Guard privateAggregation object for permissions and availability

- spec.bs
This will allow for simpler testing, by avoiding the significant reporting delays. See also the related
https://github.com/WICG/attribution-reporting-api/pull/843
***
<a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/pull/64.html" title="Last updated on Jul 10, 2023, 3:10 PM UTC (7eb661c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/64/5c9754a...7eb661c.html" title="Last updated on Jul 10, 2023, 3:10 PM UTC (7eb661c)">Diff</a>
> Spec: Add WebDriver extension

- README.md
Clarify that limits are inherently a rate, not an absolute number. Addresses comments raised in #23.
> Improving description of contribution limits

- spec.bs
This is causing some bikeshed errors now.
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Aug 15, 2023, 9:17 PM UTC)_.
<details>
<summary>More</summary>
PR Preview relies on a number of web services to run. There seems to be an issue with the following one:
:rotating_light: [CSS Spec Preprocessor](https://api.csswg.org/bikeshed/) - CSS Spec Preprocessor is the web service used to build Bikeshed specs.
:link: [Related URL](https://api.csswg.org/bikeshed/?url=https%3A%2F%2Fraw.githubusercontent.com%2Fpatcg-individual-drafts%2Fprivate-aggregation-api%2Fb5842634d397fdadf000f3ca6ff2b5847ffb7965%2Fspec.bs&md-warning=not%20ready)
```
Error running preprocessor, returned code: 2.
FATAL ERROR: Unknown metadata key "&lt;!--- Warning". Prefix custom …
```
> Spec: removes commented out metadata

- spec.bs
Per discussion in https://github.com/speced/bikeshed-boilerplate/pull/43 and #59, we should update the spec's group from patcg to patcg-id and the status to UD.
This is blocked on the bikeshed-boilerplate PR linked above as well as https://github.com/speced/bikeshed/pull/2628.
***
<a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/pull/86.html" title="Last updated on Aug 18, 2023, 3:31 PM UTC (fd6254e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/86/ef50c13...fd6254e.html" title="Last updated on Aug 18, 2023, 3:31 PM UTC (fd6254e)">Diff</a>
> Spec: Switch to patcg-id UD

- README.md
Updates the explainer to reflect the Privacy Sandbox enrollment attestation model requirements.
See also the related spec change: #87
> Include attestation and enrollment in the explainer

- README.md
Per issue #57, we tie debug mode to third-party cookie eligibility. See also the related spec change in #90.
> Clarify when debug mode is enabled

- report_verification.md
When a context ID is set, a report should be sent even if budget is exhausted to avoid leaking information about how much budget has been used.
See also the spec change: #91.
> Still send deterministic report when budget exhausted

- README.md
Updates the explainer with the short-term and longer-term plans for padding.
See #56 for more discussion and #98 for the spec change.
> Add padding details

- report_verification.md
Updates the report verification explainer to describe our plans to reduce delays for reports with a context ID (instead of describing it as a hypothetical).
This should resolve #80.
> Detail reduced delay plans for context ID reports

- spec.bs
Adds logic that allows for debug mode to be disabled even if enableDebugMode() is called. This addresses issue #57. See also the corresponding explainer change: #93.
As a drive-by, adds an issue for an assert that is currently hit.
***
<a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/pull/90.html" title="Last updated on Sep 21, 2023, 6:32 PM UTC (8f3888c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/90/cf92221...8f3888c.html" title="Last updated on Sep 21, 2023, 6:32 PM UTC (8f3888c)">Diff</a>
> Spec: Allow debug mode to be disabled arbitrarily by the user agent.

- spec.bs
Changes behavior to avoid leaking whether the budget was denied when a context ID is set. In that case, the number of reports should be deterministic and not depend on other API calls.
See also the corresponding explainer change: #94
***
<a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/pull/91.html" title="Last updated on Sep 21, 2023, 6:32 PM UTC (b13fddc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/91/cf92221...b13fddc.html" title="Last updated on Sep 21, 2023, 6:32 PM UTC (b13fddc)">Diff</a>
> Spec: Send null reports even if budget is denied

- spec.bs
Prevents a Shared Storage operation from sending contributions after a timeout, if a context ID was used. This will allow for reducing the reporting delay for this case as it prevents the reporting time from leaking any information about how long execution took (see issue #80 and the corresponding explainer change #100).
***
<a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/pull/102.html" title="Last updated on Sep 22, 2023, 3:05 AM UTC (796a742)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/102/cf92221...796a742.html" title="Last updated on Sep 22, 2023, 3:05 AM UTC (796a742)">Diff</a>
> Spec: Timeout contributions from Shared Storage when context ID is set

- spec.bs
Instead of asserting that a debug scope exists, we should return a default value to match the implementation.
***
<a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/pull/96.html" title="Last updated on Sep 26, 2023, 9:07 PM UTC (abe2579)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/96/43a7bef...abe2579.html" title="Last updated on Sep 26, 2023, 9:07 PM UTC (abe2579)">Diff</a>
> Spec: Fix a broken debug scope assert

- spec.bs
Changes the report time for reports with a context ID to the Shared Storage timeout (see PR #102), i.e. without any randomized delay.
See issue #80 and the corresponding explainer change #100.
***
<a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/pull/103.html" title="Last updated on Sep 26, 2023, 9:11 PM UTC (506ae39)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/103/0ca85d9...506ae39.html" title="Last updated on Sep 26, 2023, 9:11 PM UTC (506ae39)">Diff</a>
> Spec: Reduce delay when a context ID is set

- spec.bs
Eliminates duplicate logic. This will also simplify supporting padding in a future change.
***
<a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/pull/97.html" title="Last updated on Sep 26, 2023, 9:09 PM UTC (4a10aed)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/97/0ca85d9...4a10aed.html" title="Last updated on Sep 26, 2023, 9:09 PM UTC (4a10aed)">Diff</a>
> Spec: Merge null contribution handling

- spec.bs
Ensures that the payload always has a fixed number of contributions by adding (0,0) contributions.
See #56 for more discussion and #95 for the corresponding spec change.
***
<a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/pull/98.html" title="Last updated on Sep 26, 2023, 9:16 PM UTC (b5bd90d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/98/a02082b...b5bd90d.html" title="Last updated on Sep 26, 2023, 9:16 PM UTC (b5bd90d)">Diff</a>
> Spec: Pad the payload with null contributions

- spec.bs
This is a temporary change to reflect the launching of aggregation coordinator selection for Attribution Reporting (which adds this identifier to all aggregatable reports, given shared code). This will be replaced by a more complete spec change that allows for aggregation coordinator selection for Private Aggregation.
***
<a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/pull/105.html" title="Last updated on Oct 4, 2023, 4:55 PM UTC (05f1003)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/105/813a62d...05f1003.html" title="Last updated on Oct 4, 2023, 4:55 PM UTC (05f1003)">Diff</a>
> Spec: Add aggregation_coordinator_origin to serialized report

- spec.bs
Adds a mechanism for choosing between multiple aggregation coordinators. See also the explainer update:
https://github.com/patcg-individual-drafts/private-aggregation-api/pull/101.
To simplify this spec change, the Protected Audience integration's get batching scope steps are modified to be lazy.
***
<a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/pull/106.html" title="Last updated on Oct 24, 2023, 3:22 PM UTC (6877279)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/106/32b7bd4...6877279.html" title="Last updated on Oct 24, 2023, 3:22 PM UTC (6877279)">Diff</a>
> Spec: Aggregation coordinator choice

- flexible_filtering.md
Details a proposal for allowing more flexible querying. See https://github.com/patcg-individual-drafts/private-aggregation-api/issues/92 for earlier discussion.
> Add more flexible contribution filtering explainer

- spec.bs
This matches the behavior of the current implementation
> Truncate not round scaled signal value

- README.md
I added the following to line 453 related to the recent PAA GCP update. PTAL and approve: 
See [allowlist](https://github.com/WICG/attribution-reporting-api/blob/main/aggregation_coordinator_origin_allowlist.md) of the aggregation service coordinator origins.
> Add link to current aggregation_coordinator_origin allowlist

- spec.bs
Adds spec handling for the per-buyer latency and statistics reporting for Protected Audience, see
https://github.com/WICG/turtledove/blob/main/FLEDGE_extended_PA_reporting.md. Some follow-up work remains and has been tracked in issues added.
***
<a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/pull/117.html" title="Last updated on Feb 22, 2024, 9:43 PM UTC (11329b8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/117/23d4eb4...11329b8.html" title="Last updated on Feb 22, 2024, 9:43 PM UTC (11329b8)">Diff</a>
> Spec: auctionBuyerKeys reporting

- spec.bs
Specs out the ability to set debug mode details for auctionReportBuyer reporting. See
https://github.com/WICG/turtledove/blob/main/FLEDGE_extended_PA_reporting.md#temporary-debugging-mechanism.
***
<a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/pull/118.html" title="Last updated on Feb 22, 2024, 10:50 PM UTC (74c1a4b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/118/b09c9c4...74c1a4b.html" title="Last updated on Feb 22, 2024, 10:50 PM UTC (74c1a4b)">Diff</a>
> Spec: auctionReportBuyerDebugModeConfig

- spec.bs
Fixes some minor issues discovered in the spec where behavior did not exactly align with the implementation. Also adds some Issue comments to track some potential future improvements (e.g. aligning error types).
***
<a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/pull/122.html" title="Last updated on Mar 29, 2024, 3:01 PM UTC (5722299)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/122/4552911...5722299.html" title="Last updated on Mar 29, 2024, 3:01 PM UTC (5722299)">Diff</a>
> Spec: minor fixes

- spec.bs
These variables were used for indexing into global maps, but are not necessary.
***
<a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/pull/127.html" title="Last updated on May 1, 2024, 4:23 PM UTC (f6499e0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/127/e4ab73c...f6499e0.html" title="Last updated on May 1, 2024, 4:23 PM UTC (f6499e0)">Diff</a>
> Spec: clean up temporary variables

- spec.bs
This new struct will be used for the filtering ID handling in a follow-up spec change. This PR also factors out the determination of whether a report should be sent deterministically into its own algorithm to simplify the future change. This PR should be a no-op.
***
<a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/pull/128.html" title="Last updated on May 2, 2024, 4:24 PM UTC (d3f4c99)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/128/d94d9e8...d3f4c99.html" title="Last updated on May 2, 2024, 4:24 PM UTC (d3f4c99)">Diff</a>
> Spec: Wrap context IDs in a "pre-specified report parameters" object

- spec.bs
Specs the ability to set a filtering ID (and modify the default ID space). See https://github.com/patcg-individual-drafts/private-aggregation-api/blob/main/flexible_filtering.md#proposal-filtering-id-in-the-encrypted-payload and issue #92.
To support this new functionality, we increase the report version. Note that this also requires aggregation service versions to support the new version.
***
<a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/pull/123.html" title="Last updated on May 2, 2024, 4:29 PM UTC (3df2e53)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/123/e03bedb...3df2e53.html" title="Last updated on May 2, 2024, 4:29 PM UTC (3df2e53)">Diff</a>
> Spec: filtering IDs

- flexible_filtering.md
Updates the variable name (ByteSize -> MaxBytes), the limit on the ID space (from 32 bits/4 bytes to 64 bits/8 bytes) and to make the filteringId's type a bigint.
> Minor updates to filtering ID explainer

- README.md
The spec defines [method steps for enableDebugMode()](https://patcg-individual-drafts.github.io/private-aggregation-api/#dom-privateaggregation-enabledebugmode). These steps indicate that the method should throw a `DataError` exception when it has already been called in the current scope.
> Align enableDebugMode() semantics in explainer with spec

- README.md
Just spicing up the code blocks. PTAL, @alexmturner.
> Add "js" info string to unmarked code blocks

- spec.bs
Adds support for merging contributions with the same bucket and filtering ID before truncating to the contribution limit.
***
<a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/pull/136.html" title="Last updated on Jun 28, 2024, 6:20 PM UTC (6a21776)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/136/a321c7c...6a21776.html" title="Last updated on Jun 28, 2024, 6:20 PM UTC (6a21776)">Diff</a>
> Spec: client-side contribution merging

- .github/workflows/validate.yml
This change converts the "Preview" job into a "Validate" job. It still runs for every PR, but it does not deploy to the gh-pages branch.
Fixes #148
***
<a href="https://pr-preview.s3.amazonaws.com/dmcardle/private-aggregation-api/pull/149.html" title="Last updated on Jul 26, 2024, 3:35 PM UTC (7f5429c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/149/11c6711...dmcardle:7f5429c.html" title="Last updated on Jul 26, 2024, 3:35 PM UTC (7f5429c)">Diff</a>
> [CI] Change preview.yml to validate.yml

- spec.bs
The algorithm takes a long when it should just take an integer (as the sum of many longs may not fit in a long).
***
<a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/pull/152.html" title="Last updated on Aug 1, 2024, 6:25 PM UTC (d844e5b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/152/b87549a...d844e5b.html" title="Last updated on Aug 1, 2024, 6:25 PM UTC (d844e5b)">Diff</a>
> Spec: Fix minor type issue in consume budget if permitted

- spec.bs
The Bikeshed Documentation (dated 8 March 2024) says, "Algorithms can be explicitly indicated in your markup by putting the algorithm attribute on a container element or a heading" [1].
Through trial and error, I discovered that algorithm-specific markup is not generated when you write `<dfn algorithm>`. Instead, the `<dfn>` tag must be wrapped in something like `<div algorithm>`.
This change has at least two positive results:
1. Local variables are no longer declared in the global scope!
2. We can now click on local variables and they are highlighted in pretty colors.
[1]: https://speced.github.io/bikeshed/#var-and-algorithms
***
<a href="https://pr-preview.s3.amazonaws.com/dmcardle/private-aggregation-api/pull/147.html" title="Last updated on Aug 19, 2024, 2:59 PM UTC …
> Spec: Fix algorithm declarations

- README.md
This PR corresponds to
* "*Increase default report size for Protected Audience callers*" in <https://github.com/patcg-individual-drafts/private-aggregation-api/issues/81#issuecomment-2091524214>.
* The spec change in #150
@alexmturner PTAL!
***
<a href="https://pr-preview.s3.amazonaws.com/dmcardle/private-aggregation-api/pull/138.html" title="Last updated on Jul 1, 2024, 10:07 PM UTC (075b203)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/138/969c944...dmcardle:075b203.html" title="Last updated on Jul 1, 2024, 10:07 PM UTC (075b203)">Diff</a>
> Describe per-calling-API contribution count limits in explainer

- flexible_filtering.md
- report_verification.md
We plan to not allow setting the `contextId` and `filteringIdMaxBytes` from within a fenced frame when calling Shared Storage operations as that can be used to exfiltrate information.
Spec PR: https://github.com/patcg-individual-drafts/private-aggregation-api/pull/151
> Update explainers for fenced frame privateAggregationConfig restrictions.

- spec.bs
This PR corresponds to
* "*Increase default report size for Protected Audience callers*" in <https://github.com/patcg-individual-drafts/private-aggregation-api/issues/81#issuecomment-2091524214>.
* The explainer change in PR #138.
~~Note that this PR depends on #149. (GitHub doesn't understand dependent PRs, so this appears to include its parent's changes.)~~
***
<a href="https://pr-preview.s3.amazonaws.com/dmcardle/private-aggregation-api/pull/150.html" title="Last updated on Sep 3, 2024, 4:14 PM UTC (5c54351)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/150/9108e9b...dmcardle:5c54351.html" title="Last updated on Sep 3, 2024, 4:14 PM UTC (5c54351)">Diff</a>
> Spec: Define per-calling-API limit on contributions per report

- Makefile
Although the spec is already compiled automatically by CI and GitHub renders our Markdown, I still find it useful to automate commands that I frequently use in local development. A Makefile is better than another Markdown file because it's executable!
> Add Makefile for local dev: building spec, rendering Markdown, etc.

- spec.bs
The version that takes a USVString is shared between Protected Audience and Shared Storage, so we can export it. Updates links so that the monkey patched version has a modified linking text as that will be removed from this spec soon.
***
<a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/pull/163.html" title="Last updated on Oct 17, 2024, 10:04 PM UTC (217a8e2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/163/f5cda2b...217a8e2.html" title="Last updated on Oct 17, 2024, 10:04 PM UTC (217a8e2)">Diff</a>
> Spec: export obtain the Private Aggregation coordinator algorithm

- README.md
Updates the language to only allow debug mode if third-party cookies are generally enabled for a user, ignoring when they are only enabled for a specific site.
> Update explainer to ignore site exceptions for debug mode eligibility

- README.md
~~This PR depends on #138. (GitHub doesn't understand dependent PRs, so this appears to include its parent's changes.)~~
This change is a little larger than it had to be, but I think it was time to add some structure to the section. WDYT, @alexmturner?
> Describe per-context limits in explainer

- named_budgets.md
This introduces a new feature proposal to better support splitting the Private Aggregation budget between different use cases or products.
> Add named budgets explainer

- spec.bs
This change adds the web-visible `maxContributions` field, which enables some callers to request different numbers of contributions per report.
Per-context limits are being added to the explainer in #146.
***
<a href="https://pr-preview.s3.amazonaws.com/dmcardle/private-aggregation-api/pull/164.html" title="Last updated on Jan 15, 2025, 5:58 PM UTC (8472d3b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/164/1e6db01...dmcardle:8472d3b.html" title="Last updated on Jan 15, 2025, 5:58 PM UTC (8472d3b)">Diff</a>
> Spec: Define per-context contribution limits

- spec.bs
It's not necessary to send a null report when the caller-provided "max contributions" has no effect on the payload length.
This commit updates the algorithm "determine if a report should be sent deterministically" to account for this edge case. Relatedly, it also updates the prose description of payload-length side channel.
> Spec: Weaken null report requirement WRT max contributions

- spec.bs
Adds support for aggregate error reporting. Additional changes are required to the embedding APIs' specs to support the feature.
***
<a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/pull/172.html" title="Last updated on Feb 28, 2025, 11:18 PM UTC (65d4e73)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/172/d612b5c...65d4e73.html" title="Last updated on Feb 28, 2025, 11:18 PM UTC (65d4e73)">Diff</a>
> Spec: Aggregate error reporting

- spec.bs
We should instead link to the original webdriver definition as used in the webdriver spec. Also adds the arguments to the definition.
***
<a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/pull/174.html" title="Last updated on Feb 28, 2025, 5:12 PM UTC (ed744ae)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/174/d612b5c...ed744ae.html" title="Last updated on Feb 28, 2025, 5:12 PM UTC (ed744ae)">Diff</a>
> Spec: don't export / define "remote end steps"

- spec.bs
There are a range of definitions used in other specs that aren't exported yet.
***
<a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/pull/175.html" title="Last updated on Mar 4, 2025, 7:30 PM UTC (a57f44c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/175/3720046...a57f44c.html" title="Last updated on Mar 4, 2025, 7:30 PM UTC (a57f44c)">Diff</a>
> Spec: export more definitions
