patcg-individual-drafts/private-aggregation-api

README.md
Adds a temporary debugging mechanism. Also provides more detail on the report format and specifies the report endpoint URL paths. Resolves #4, #6, #8.
=> Add debug mode and more detail

README.md
=> Support batching

spec.bs
Mostly formatting and small prose changes
***
<a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/pull/26.html" title="Last updated on Apr 19, 2023, 4:04 PM UTC (5bedb60)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/26/6a71a39...5bedb60.html" title="Last updated on Apr 19, 2023, 4:04 PM UTC (5bedb60)">Diff</a>
=> Minor spec updates

.gitignore
Prevent the bikeshed.html file from being tracked by git
=> Add compiled bikeshed to .gitignore

report_verification.md
Wrap the context ID in a more generic config to allow future extension
=> Minor shared storage example update

spec.bs
Heavily based off the Attribution Reporting API spec
***
<a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/pull/28.html" title="Last updated on May 3, 2023, 9:37 PM UTC (3cc328d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/28/5ca6783...3cc328d.html" title="Last updated on May 3, 2023, 9:37 PM UTC (3cc328d)">Diff</a>
=> Spec: Add report sending logic

spec.bs
This should help with readability and simplify looking at diffs of future commits. This should not cause any change in the rendered version except for two line breaks in IDL definitions.
***
<a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/pull/33.html" title="Last updated on May 3, 2023, 10:11 PM UTC (f8810e7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/33/b814811...f8810e7.html" title="Last updated on May 3, 2023, 10:11 PM UTC (f8810e7)">Diff</a>
=> Spec: Wrap lines to 80 characters

README.md
=> Limit number of contributions to 20 per report

README.md
=> Update references to FLEDGE in explainer

README.md
=> Change debug key to camelCase

security_and_privacy_questionnaire.md
A link was accidentally omitted
=> Fix link in security_and_privacy_questionnaire.md

spec.bs
Adds two non-normative sections discussing privacy and security considerations
***
<a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/pull/53.html" title="Last updated on Jun 9, 2023, 7:58 PM UTC (906cd62)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/53/3d32307...906cd62.html" title="Last updated on Jun 9, 2023, 7:58 PM UTC (906cd62)">Diff</a>
=> Spec: Add Privacy and Security considerations sections

spec.bs
Introduces the debug mode to the spec and the concept of a 'debug scope'
***
<a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/pull/60.html" title="Last updated on Jun 13, 2023, 6:14 PM UTC (8d29739)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/60/e79ff12...8d29739.html" title="Last updated on Jun 13, 2023, 6:14 PM UTC (8d29739)">Diff</a>
=> Spec: Add enableDebugMode()

spec.bs
Resolves #42.
***
<a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/pull/65.html" title="Last updated on Jun 15, 2023, 4:24 PM UTC (4c5f2e4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/65/fbc6b42...4c5f2e4.html" title="Last updated on Jun 15, 2023, 4:24 PM UTC (4c5f2e4)">Diff</a>
=> Spec: Add fetch()-style API as a considered alternative

spec.bs
Allow a context ID to be set by Shared Storage
***
<a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/pull/62.html" title="Last updated on Jun 15, 2023, 4:34 PM UTC (2b8d4ca)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/62/b0d2cf6...2b8d4ca.html" title="Last updated on Jun 15, 2023, 4:34 PM UTC (2b8d4ca)">Diff</a>
=> Spec: add context ID support

spec.bs
Mostly just small changes to prose, layouts and removing stale issues.
***
<a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/pull/68.html" title="Last updated on Jun 20, 2023, 8:28 PM UTC (8c72a2a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/68/30284c9...8c72a2a.html" title="Last updated on Jun 20, 2023, 8:28 PM UTC (8c72a2a)">Diff</a>
=> Spec: miscellaneous improvements

spec.bs
Addresses comments raised in #63.
***
<a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/pull/71.html" title="Last updated on Jun 21, 2023, 4:03 PM UTC (d42c1ed)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/71/e75017b...d42c1ed.html" title="Last updated on Jun 21, 2023, 4:03 PM UTC (d42c1ed)">Diff</a>
=> Spec: Improve Protected Audience extensions plumbing

README.md
The current wording is a little confusing.
=> Clarify the intended contribution bounds

README.md
=> Add mechanism for choosing between multiple aggregation coordinators

README.md, spec.bs
@alexmt PTAL
***
<a href="https://pr-preview.s3.amazonaws.com/dmcardle/private-aggregation-api/pull/137.html" title="Last updated on Jul 1, 2024, 8:10 PM UTC (e9b3822)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/137/969c944...dmcardle:e9b3822.html" title="Last updated on Jul 1, 2024, 8:10 PM UTC (e9b3822)">Diff</a>
=> Fix minor typos in README.md and spec.bs

spec.bs
Fixes #157.
***
<a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/pull/159.html" title="Last updated on Aug 28, 2024, 6:12 PM UTC (997374b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/159/a53a027...997374b.html" title="Last updated on Aug 28, 2024, 6:12 PM UTC (997374b)">Diff</a>
=> Fix broken link in spec monkey patch

.github/workflows/validate.yml
Switch to using the w3c version of spec-prod
=> Update validate.yml to use w3c's spec-prod

Makefile
=> Add recipe to Makefile that generates an "exports" report

spec.bs
***
<a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/pull/177.html" title="Last updated on Mar 7, 2025, 7:00 PM UTC (a1d6e8f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/patcg-individual-drafts/private-aggregation-api/177/7bd9d6f...a1d6e8f.html" title="Last updated on Mar 7, 2025, 7:00 PM UTC (a1d6e8f)">Diff</a>
=> Spec: export fields of contribution cache entry
